### ISSUE TITLE
Add link preview metadata to HTML

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/frontpage#10]

**Comment by glenn-sorrentino** [comment]
added, live on site now:

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#333333">
    <title>{{ title|default('Default Title') }} - Distributed Denial of Secrets</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    
    <meta name="description" content="A 501(c)(3) dedicated to archiving and publishing hacked and leaked data.">
    <meta property="og:title" content="{{ title }} - Distributed Denial of Secrets">
    <meta property="og:description" content="A 501(c)(3) dedicated to archiving and publishing hacked and leaked data.">
    
    <meta property="og:url" content="{{ request.url }}">
    <meta name="twitter:card" content="summary_large_image">
</head>
