### ISSUE TITLE
New articles should accpt a size string but store download as an INT in the DB

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/frontpage#7]
I want to enter sizes as `42GB` or `1.2TiB` and then have them consistently displayed on every page.

**Comment by glenn-sorrentino** [comment]
Completed, live on the site now. 

Resulted in setting DB history back to before you added your first article, @brassy-endomorph.

**Comment by glenn-sorrentino** [comment]
https://github.com/scidsg/frontpage/commit/1ba4ccfc1bfd06b6119b8a3d995f915efa85216f
